In [1]:
import pandas as pd

In [17]:
bikes = pd.read_csv('day.csv')
bikes.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [3]:
from statsmodels.formula.api import ols

In [16]:
bikes_model = ols('cnt ~ temp + atemp', bikes ).fit()
bikes_model

In [47]:
print(bikes_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    cnt   R-squared:                       0.398
Model:                            OLS   Adj. R-squared:                  0.397
Method:                 Least Squares   F-statistic:                     241.1
Date:                Mon, 16 Aug 2021   Prob (F-statistic):           4.62e-81
Time:                        22:06:18   Log-Likelihood:                -6383.9
No. Observations:                 731   AIC:                         1.277e+04
Df Residuals:                     728   BIC:                         1.279e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    981.0365    188.362      5.208      0.000     611.238    1350.835
temp        1066.2120   2366.347      0.451      0.652   -3579.466    5711.890
atemp       6314.1183   2658.070      2.375      0.018    1095.722    1.15e+04
==============================================================================
Omnibus:                       15.838   Durbin-Watson:                   0.473
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               10.302
Skew:                           0.148   Prob(JB):                      0.00579
Kurtosis:                       2.499   Cond. No.                         77.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Create a for loop that measures the coefficient for all the values in the with the `cnt` variable.

In [27]:
bikes.select_dtypes([int, float])

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,727,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867,2114
727,728,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451,3095
728,729,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182,1341
729,730,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432,1796
730,731,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290,2729

Study and perform EDA on the bikes dataset.

Write a loop that iterates through all the columns in the dataframe and returns the pearson coefficient for all numerical values.

In [39]:
import scipy.stats as st

for i in bikes.select_dtypes([int, float]):
    print(f" {i}: {st.pearsonr(bikes[i], bikes['cnt'])[0]}")

 instant: 0.6288302722083061
 season: 0.4061003707986359
 yr: 0.5667097078680867
 mnth: 0.27997711221927124
 holiday: -0.0683477158924842
 weekday: 0.06744341241063048
 workingday: 0.06115606306052078
 weathersit: -0.29739123883466345
 temp: 0.627494009033492
 atemp: 0.6310656998491813
 hum: -0.10065856213715527
 windspeed: -0.23454499742167
 casual: 0.6728044333386831
 registered: 0.9455169158090356
 cnt: 0.9999999999999999

Create a function that takes in any independent variable (that is numerical), fits a model with your target variable, and prints out only the slope, the intercept, and the p_value.

In [71]:
def model_maker(feature):
    from statsmodels.formula.api import ols
    model = ols(f'cnt ~ {feature}', bikes ).fit()
    print(model.params[0], model.params[1], st.pearsonr(bikes[i], bikes['cnt'])[1])

In [72]:

model_maker('season')

2736.2063446742445 708.2258422154132 0.0

Choose an appropriate feature to use for a linear model. Describe the results.

Does calculating the results with the logarithmic value improve your model?